# Generated by Django 5.2.5 on 2025-10-11 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('layout', models.JSONField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('timer', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(max_length=10)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='levels/preview_imgs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='levelattempt',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level'),
        ),
        migrations.DeleteModel(
            name='Levels',
        ),
    ]
