# Generated by Django 5.2.7 on 2025-10-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_level_alter_levelattempt_level_id_delete_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='layout',
        ),
        migrations.AddField(
            model_name='level',
            name='layout_file',
            field=models.FileField(default=None, upload_to='jumpio-levels/layouts/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='level',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='jumpio-levels/preview_imgs'),
        ),
    ]
