# Generated by Django 5.2.7 on 2025-10-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_remove_level_layout_level_layout_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='layout_file',
            field=models.FileField(upload_to='layouts/'),
        ),
        migrations.AlterField(
            model_name='level',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='preview_imgs'),
        ),
    ]
