# Generated by Django 5.2.10 on 2026-01-19 17:13

import levels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0005_alter_level_layout_file_alter_level_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='layout_file',
            field=models.FileField(upload_to=levels.models.layout_upload_path),
        ),
        migrations.AlterField(
            model_name='level',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to=levels.models.preview_upload_path),
        ),
    ]
